name: GitHub Metrics

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/metrics.yml
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          config_timezone: Asia/Seoul
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
