name: Snake Animation

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/snake.yml
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: sooyeol2g
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit generated SVGs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f dist
          git diff --staged --quiet && exit 0
          git commit -m "chore: update snake animation"
          git push
